apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: junior-rb-production
  namespace: production
subjects:
- kind: Group
  name: junior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
