apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: senior-rb-test
  namespace: test
subjects:
- kind: Group
  name: senior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
